using EduCycle.Domain.Entities;
using EduCycle.Domain.Enums;
using Microsoft.EntityFrameworkCore;

namespace EduCycle.Infrastructure.Data;

public class ApplicationDbContext : DbContext
{
    public ApplicationDbContext(DbContextOptions<ApplicationDbContext> options)
        : base(options) { }

    public DbSet<User> Users => Set<User>();
    public DbSet<Product> Products => Set<Product>();
    public DbSet<Category> Categories => Set<Category>();
    public DbSet<Transaction> Transactions => Set<Transaction>();
    public DbSet<Review> Reviews => Set<Review>();
    public DbSet<Message> Messages => Set<Message>();

    protected override void OnModelCreating(ModelBuilder modelBuilder)
    {
        // ===== REVIEW =====

        modelBuilder.Entity<Review>()
            .HasOne(r => r.User)
            .WithMany()
            .HasForeignKey(r => r.UserId)
            .OnDelete(DeleteBehavior.NoAction);

        modelBuilder.Entity<Review>()
            .HasOne(r => r.Product)
            .WithMany()
            .HasForeignKey(r => r.ProductId)
            .OnDelete(DeleteBehavior.Cascade);

        // ===== TRANSACTION =====

        modelBuilder.Entity<Transaction>()
            .HasOne(t => t.Buyer)
            .WithMany()
            .HasForeignKey(t => t.BuyerId)
            .OnDelete(DeleteBehavior.NoAction);

        modelBuilder.Entity<Transaction>()
            .HasOne(t => t.Seller)
            .WithMany()
            .HasForeignKey(t => t.SellerId)
            .OnDelete(DeleteBehavior.NoAction);

        modelBuilder.Entity<Transaction>()
            .HasOne(t => t.Product)
            .WithMany()
            .HasForeignKey(t => t.ProductId)
            .OnDelete(DeleteBehavior.NoAction);

        modelBuilder.Entity<Transaction>()
            .Property(t => t.Status)
            .HasConversion<string>()
            .HasMaxLength(20);

        // ===== PRODUCT → CATEGORY =====

        modelBuilder.Entity<Product>()
            .HasOne<Category>()
            .WithMany(c => c.Products)
            .HasForeignKey(p => p.CategoryId)
            .OnDelete(DeleteBehavior.SetNull);

        modelBuilder.Entity<Product>()
            .HasOne(p => p.User)
            .WithMany()
            .HasForeignKey(p => p.UserId)
            .OnDelete(DeleteBehavior.Cascade);

        // ===== PRODUCT STATUS =====

        modelBuilder.Entity<Product>()
            .Property(p => p.Status)
            .HasConversion<string>()
            .HasMaxLength(20);

        // ===== MESSAGE =====

        modelBuilder.Entity<Message>()
            .HasOne(m => m.Transaction)
            .WithMany()
            .HasForeignKey(m => m.TransactionId)
            .OnDelete(DeleteBehavior.Cascade);

        modelBuilder.Entity<Message>()
            .HasOne(m => m.Sender)
            .WithMany()
            .HasForeignKey(m => m.SenderId)
            .OnDelete(DeleteBehavior.NoAction);

        // ===== DECIMAL PRECISION =====

        modelBuilder.Entity<Product>()
            .Property(p => p.Price)
            .HasPrecision(18, 2);

        modelBuilder.Entity<Transaction>()
            .Property(t => t.Amount)
            .HasPrecision(18, 2);

        // ===== USER ROLE =====

        modelBuilder.Entity<User>()
            .Property(u => u.Role)
            .HasConversion<string>()
            .HasMaxLength(20);

        // ===== SEED ADMIN =====
        // Password: admin@1
        // Hash generated by BCrypt.Net.BCrypt.HashPassword("admin@1")

        modelBuilder.Entity<User>().HasData(new User
        {
            Id = Guid.Parse("00000000-0000-0000-0000-000000000001"),
            Username = "admin",
            Email = "admin@educycle.com",
            PasswordHash = "$2a$11$vI8aWBnW3fID.ixJCRy.qOhMkGh/.WY6g9E7KO0OLfZNPq9i0jq9y", // admin@1
            Role = Role.Admin,
            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, DateTimeKind.Utc)
        });

        // ===== SEED CATEGORIES =====

        modelBuilder.Entity<Category>().HasData(
            new Category { Id = 1, Name = "Giáo Trình" },
            new Category { Id = 2, Name = "Sách Chuyên Ngành" },
            new Category { Id = 3, Name = "Tài Liệu Ôn Thi" },
            new Category { Id = 4, Name = "Dụng Cụ Học Tập" },
            new Category { Id = 5, Name = "Ngoại Ngữ" },
            new Category { Id = 6, Name = "Khác" }
        );
    }
}
